theme = "autumn_night"

[editor]
	# scrolloff = 999
	line-number = "relative"
	bufferline = "multiple"

	[editor.cursor-shape]
		insert = "bar"
		select = "underline"

	[editor.indent-guides]
		# render = true
		character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
		skip-levels = 1

	[editor.whitespace]
		# render = "all"
		[editor.whitespace.characters]
			space = "·"
			tab = "-"
			# tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

# create a new minor mode bound to `+`
[keys.normal."z"]
	o = ":run-shell-command zed"
