theme = "ayu_evolve"

[editor]
	lsp.enable = false # This turns off all LSP features for all languages
	# scrolloff = 999
	auto-format = false
	line-number = "relative"
	bufferline = "multiple"

	[editor.cursor-shape]
		insert = "bar"
		select = "underline"

	[editor.indent-guides]
		# render = true
		character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
		skip-levels = 1

	[editor.whitespace]
		[editor.whitespace.render]
			space = "none"
			tab = "all"
			nbsp = "none"
			nnbsp = "none"
			newline = "all"

		[editor.whitespace.characters]
			space = "·"
			tab = "-"
			newline = "¬"
			# tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

# create a new minor mode bound to `+`
[keys.normal."z"]
	o = ":run-shell-command zed"
	r = ":lsp-restart"
	"R" = ":config-reload"
