[[language]]
	name = "go"
	formatter = { command = "gopls", args = [
		"format",
		"%{buffer_name}",
	] }

[[language]]
	name = "java"
	formatter = { command = "/Library/Developer/CommandLineTools/usr/bin/clang-format", args = [
		"--configuration=/Users/pritam/Developer/git_repository/dotfiles/global/c-cpp-template/c++/.clang-format-java",
		"--assume-filename=%{buffer_name}",
	] }

[[language]]
	name = "cmake"
	formatter = { command = "neocmakelsp", args = ["format", "%{buffer_name}"] }

[[language]]
	name = "cmake"
	formatter = { command = "neocmakelsp", args = ["format", "%{buffer_name}"] }

[[language]]
	name = "c"
	formatter = { command = "/Library/Developer/CommandLineTools/usr/bin/clang-format", args = [
		"--style=file:/Users/pritam/Developer/git_repository/dotfiles/global/c-cpp-template/c/.clang-format",
		"--assume-filename=%{buffer_name}",
	] }

[[language]]
	name = "cpp"
	formatter = { command = "/Library/Developer/CommandLineTools/usr/bin/clang-format", args = [
		"--configuration=/Users/pritam/Developer/git_repository/dotfiles/global/c-cpp-template/c++/.clang-format",
		"--assume-filename=%{buffer_name}",
	] }

[[language]]
	name = "json"
	formatter = { command = "/Library/Developer/CommandLineTools/usr/bin/clang-format", args = [
		"--configuration=/Users/pritam/Developer/git_repository/dotfiles/global/c-cpp-template/c++/.clang-format",
		"--assume-filename=%{buffer_name}",
	] }

[[language]]
	name = "jsonc"
	formatter = { command = "/Library/Developer/CommandLineTools/usr/bin/clang-format", args = [
		"--configuration=/Users/pritam/Developer/git_repository/dotfiles/global/c-cpp-template/c++/.clang-format",
		"--assume-filename=%{buffer_name}",
	] }

[[language]]
	name = "python"
	formatter = { command = "ruff", args = [
		"format",
		"--config=~/.config/ruff/ruff.toml",
		"--stdin-filename=%{buffer_name}",
	] }

[[language]]
	name = "xml"
	formatter = { command = "/Users/pritam/.config/tidy/tidy-xml.sh", args = ["%{buffer_name}"] }

[[language]]
	name = "sql"
	formatter = { command = "sleek", args = [] }

[language-server.tinymist]
	command = "tinymist"

	config = { preview.background.enabled = true, preview.background.args = [
		"--data-plane-host=127.0.0.1:23635",
	"--invert-colors='{'rest': 'always', 'image': 'never'}'",
		"--open",
	] }

	# "--invert-colors=never",
	# "--invert-colors='{'rest': 'always', 'image': 'never'}'",

	# formatterIndentSize = 4
	# formatterMode = "typstyle"
	# compileStatus = "enable"
